services:
  db:
    image: postgres:16
    container_name: lead_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lead
    ports:
      - "5432:5432"
    volumes:
      - lead_db_data:/var/lib/postgresql/data

volumes:
  lead_db_data:
